export const dummyInbox = [
    {
        id: '1',
        userId: '1',
        userName: 'Phillips',
        title: '1012312 - Test Channel',
        date: '02/06/2021 10:45',
        isGroupChannel: true,
        users: [
            {
                userid: '1',
                userName: 'Phillips',
            },
            {
                userid: '2',
                userName: 'Cameron',
            },
            {
                userId: '3',
                userName: 'Obaidullah Amarkhil',
            }
        ],
        body: 'I understand your initial concerns and thats very valid, Elizabeth. But you understand your initial concerns and thats very valid.',
        status: 'unread',
    },
    {
        id: '2',
        userId: '1',
        userName: 'Mary Hilda',
        title: 'Jeannette Moraima Guaman Chamba (Hutto I-589) [ Hutto Follow Up - Brief Service ]',
        date: '02/06/2021 10:45',
        isGroupChannel: true,
        users: [
            {
                userid: '1',
                userName: 'Phillips',
            },
            {
                userid: '2',
                userName: 'Cameron',
            },
        ],
        body: 'Sure thing, Claren.',
        status: 'unread',
    },
    {
        id: '3',
        userId: '1',
        userName: 'FastVisa Support',
        title: 'FastVisa Support',
        date: '01/06/2021 12:19',
        isGroupChannel: false,
        users: [
            {
                userid: '3',
                userName: 'FastVisa Support',
            },
        ],
        body: 'Hey there! Welcome to your inbox.!',
        status: 'read',
    },
]

export const dummyChat = [
    {
        id: '1',
        body: 'No worries. It will be complited!',
        date: '02/06/2021',
        time: '19:32',
        status: 'read',
        userId: '1',
        name: 'Phillips',
        inboxId: '1',
        isEdited: false,
    },
    {
        id: '2',
        body: 'Hello Obaidullah, I will be your case advisor for case #029290. I have assigned some homework for you to fill. Please keep up with the due dates. Should you have any questions, you can message me anytime. Thanks.',
        date: '03/06/2021',
        time: '19:32',
        status: 'read',
        userId: '2',
        name: 'Mary Hilda',
        inboxId: '1',
        isEdited: false,
    },
    {
        id: '3',
        body: 'Please contact Mary for questions regarding the case bcs she will be managing your forms from now on! Thanks Mary.',
        date: '03/06/2021',
        time: '19:32',
        status: 'read',
        userId: '1',
        name: 'Phillips',
        inboxId: '1',
        isEdited: false,
    },
    {
        id: '4',
        body: 'Sure thing, Claren.',
        date: '04/06/2021',
        time: '19:32',
        status: 'read',
        userId: '2',
        name: 'Mary Hilda',
        inboxId: '1',
        isEdited: false,
    },
    {
        id: '5',
        body: 'Morning. I’ll try to do them. Thanks',
        date: '04/06/2021',
        time: '20:22',
        status: 'unread',
        userId: '3',
        name: 'Obaidullah Amarkhil',
        inboxId: '1',
        isEdited: false,
    },
    {
        id: '6',
        body: 'Just Fill me in for his updates yea?',
        date: '03/06/2021',
        time: '19:32',
        status: 'read',
        userId: '2',
        name: 'Mary Hilda',
        inboxId: '2',
        isEdited: false,
    },
    {
        id: '7',
        body: 'No worries. It will be completed ASAP. I’ve asked him yesterday.',
        date: '04/06/2021',
        time: '19:32',
        status: 'read',
        userId: '1',
        name: 'Phillips',
        inboxId: '2',
        isEdited: false,
    },
    {
        id: '8',
        body: 'Hello Obaidullah, I will be your case advisor for case #029290. I have assigned some homework for you to fill. Please keep up with the due dates. Should you have any questions, you can message me anytime. Thanks.',
        date: '04/06/2021',
        time: '20:22',
        status: 'read',
        userId: '2',
        name: 'Mary Hilda',
        inboxId: '2',
        isEdited: false,
    },
    {
        id: '9',
        body: 'Please contact Mary for questions regarding the case bcs she will be managing your forms from now on! Thanks Mary.',
        date: '05/06/2021',
        time: '20:22',
        status: 'read',
        userId: '1',
        name: 'Phillips',
        inboxId: '2',
        isEdited: false,
    },
    {
        id: '10',
        body: 'Sure thing, Claren.',
        date: '05/06/2021',
        time: '20:22',
        status: 'unread',
        userId: '2',
        name: 'Mary Hilda',
        inboxId: '2',
        isEdited: false,
    },
    {
        id: '11',
        body: 'Hi there. Welcome to your inbox! Contact us for more information and help about anything! We will send you a response as soon as posibble.',
        date: '05/06/2021',
        time: '19:32',
        status: 'read',
        userId: '4',
        name: 'FastVisa Support',
        inboxId: '3',
        isEdited: false,
    },
    {
        id: '12',
        body: 'Hello FastVisa Support',
        date: '05/06/2021',
        time: '20:22',
        status: 'read',
        userId: '1',
        name: 'Phillips',
        inboxId: '3',
        isEdited: false,
    },
    {
        id: '13',
        body: 'Hi, I need help with something can you help me?',
        date: '05/06/2021',
        time: '20:25',
        status: 'read',
        userId: '1',
        name: 'Phillips',
        inboxId: '3',
        isEdited: false,
    },
    {
        id: '14',
        body: 'Sure thing, Claren.',
        date: '05/06/2021',
        time: '20:32',
        status: 'unread',
        userId: '4',
        name: 'FastVisa Support',
        inboxId: '3',
        isEdited: false,
    },
]